---
extends:
  - 'eslint:recommended'
  - 'plugin:node/recommended'
  - prettier
plugins:
  - node
  - prettier
  - mocha
env:
  node: true
  es6: true
  mocha: true
parserOptions:
  ecmaVersion: 2018
rules:
  mocha/no-exclusive-tests: error
  prettier/prettier: error
  block-scoped-var: error
  eqeqeq: error
  no-warning-comments: warn
  no-var: error
  no-console: off
  no-process-exit: off
  max-len:
    - error
    - code: 120
      ignoreUrls: true
